# Generated by Django 4.0.2 on 2022-02-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Okved',
            fields=[
                ('okved', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'okveds',
            },
        ),
    ]
